services:
  - type: web
    name: smart-minutes
    runtime: node
    repo: https://github.com/WadoTeamAI/smart-minutes
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000